# Site Info
title:              "AnayAlvis"
description:        "AnayAlvis on Science, maths and tech."

# Google APIs
google_verify:      false# Your Google Verification - set to 'false' to disable
google_analytics:   UA-120512630-1 # Your Google Analytics code - set to 'false' to disable

# Author Info
author_name:        "AnayAlvis"
author_email:       anu25270@gmail.com
author_gravatar:    false # Gravatar md5 hash (of email) here for logo - set to 'false' to disable
twitter_username:   false # set to 'false' to disable
github_username:    false # set to 'false' to disable

# Site Settings
url:                https://anayalvis.github.io # main url
baseurl:            / # for gh-pages
permalink:          /notes/:title # Post permalink
timezone:           Asia/Kuala_Lumpur # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
# plugins:
#   - jekyll-sitemap

plugins:
  - jekyll-remote-theme

remote_theme: heiswayi/the-plain

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
